### ISSUE TITLE
Fung tong นี่มันคืออะไร?

### ISSUE THREAD

**Issue by teerasej** [CutCutto/DriverMon#1]
@CutCutto ที่อยู่ในโค้ดคืออะไร?

`<Button Clicked="">`

**Comment by CutCutto** [comment]
@pancharin  ช่วยผมหน่อยครับ

**Comment by pancharin** [comment]
@CutCutto Ummm ช่วยตัวเองน่ะ

**Comment by chomravee** [comment]
test cose (Close)
